#!/bin/bash

. host.include

countStr=3
service=$1
key=$2

if [ "$service" == "" ]; then
    echo "You must supply a service name"
    exit 1
fi

if [ "$key" == "" ]; then
    echo "You must supply a $service key"
    exit 1
fi

BASE_URL="`getUrl entity-gateway ${service}`/${service}s/${key}"

# https://github.com/jkbr/httpie
echo "http DELETE ${BASE_URL} ${HEADERS}"
time http DELETE ${BASE_URL} ${HEADERS}

