#!/bin/bash

. host.include

countStr=3
service=$1

if [ "$service" == "" ]; then
    echo "You must supply a service name"
    exit 1
fi

filter=$2

BASE_URL=`getUrl entity-gateway`/${service}s
#BASE_URL=http://customer-dev.connectedfleet.io:8080/${service}s

PARAMS="page==0 pageSize==10 sortField==name"

if [ "$filter" != "" ]; then
    PARAMS="$PARAMS q==${filter}"
fi

# https://github.com/jkbr/httpie
echo "http GET ${BASE_URL} ${HEADERS} ${PARAMS}"
time http GET ${BASE_URL} ${HEADERS} ${PARAMS}

